---
title: "Module 3: Individual Claims Size Modelling"
output: html_notebook
---

**3.4.3**

```{r}
claims = c(132, 149, 476, 147, 135, 110, 176, 107, 147, 165,
135, 117, 110, 111, 226, 108, 102, 108, 227, 102)
theta = 100
alpha = length(claims)/sum(log(claims/theta))
alpha

0.5^alpha
```

**3.4.4**
```{r}
library(fitdistrplus)
library(actuar)

claims = c(52.8, 78.5, 135.2, 75.3, 55.9, 178.3, 138.6, 182.8, 122.9, 54.4,
           55.8, 365.3, 368.2, 1051.1, 83.8)
theta = 50
alpha = length(claims)/sum(log(claims/theta))
alpha*(length(claims)-1)/length(claims)

(50/2000)^alpha

fit = fitdist(claims, "pareto", "mle", fix.arg = list(scale = 50))
summary(fit)
```
**3.5.1**

```{r}
freq = c(5, 37, 28, 31, 23, 9, 22, 17, 15, 17, 13, 12, 3, 5, 5, 3, 3)
start = c(0, 25, 50, 75, 100, 125, 150, 200, 250, 350, 500, 750, 1000,
          1500, 2500, 5000, 10000, 25000)
end = c(25 , 50 , 75 , 100 , 125 , 150 , 200 , 250 , 350 , 500 , 750 ,
        1000 , 1500 , 2500 , 5000 , 10000 , 25000, Inf)
```

**3.5.3**
```{r}
library(tidyverse)
library(fitdistrplus)
library(actuar)

liability = read_table("liability.txt")$liability
summary(liability)

plotdist(liability, demp=T)
descdist(liability, boot=1000)


# Pareto Fit
fit.pareto.mle = fitdist(liability, "pareto", "mle", lower=c(0,0))
summary(fit.pareto.mle)

par(mfrow = c(2,2))
denscomp(fit.pareto.mle, legendtext = "Pareto Fit")
cdfcomp(fit.pareto.mle, legendtext = "Pareto Fit")
ppcomp(fit.pareto.mle, legendtext = "Pareto Fit")
qqcomp(fit.pareto.mle, legendtext = "Pareto Fit")
plot.new()
par(mfrow = c(1,1))

# Weibull Fit
fit.weibull.mle = fitdist(liability, "weibull", "mle", lower=c(0,0))
summary(fit.weibull.mle)

par(mfrow = c(2,2))
denscomp(fit.weibull.mle, legendtext = "Weibull Fit")
cdfcomp(fit.weibull.mle, legendtext = "Weibull Fit")
ppcomp(fit.weibull.mle, legendtext = "Weibull Fit")
qqcomp(fit.weibull.mle, legendtext = "Weibull Fit")
plot.new()
par(mfrow = c(1,1))

# Log Normal Fit

fit.lnorm.mle = fitdist(liability, "lnorm", "mle", lower=c(0,0))
summary(fit.lnorm.mle)

par(mfrow = c(2,2))
denscomp(fit.lnorm.mle, legendtext = "Log-Normal Fit")
cdfcomp(fit.lnorm.mle, legendtext = "Log-Normal Fit")
ppcomp(fit.lnorm.mle, legendtext = "Log-Normal Fit")
qqcomp(fit.lnorm.mle, legendtext = "Log-Normal Fit")
plot.new()
par(mfrow = c(1,1))

# Plotting
denscomp(list(fit.pareto.mle, fit.weibull.mle, fit.lnorm.mle))
cdfcomp(list(fit.pareto.mle, fit.weibull.mle, fit.lnorm.mle))
ppcomp(list(fit.pareto.mle, fit.weibull.mle, fit.lnorm.mle))
qqcomp(list(fit.pareto.mle, fit.weibull.mle, fit.lnorm.mle))
plot.new()

summary(fit.pareto.mle)
summary(fit.weibull.mle)
summary(fit.lnorm.mle)

# lnorm has the best fit in terms of AIC and BIC and graphically has the best fit for around 40% of the data.
# The Pareto otherwise has the best fit for estimating the heavy tail of the data, but the fit still isnt that good.

gof.stats = gofstat(list(fit.pareto.mle, fit.weibull.mle, fit.lnorm.mle))
gof.stats$adtest
gof.stats$kstest
gof.stats$chisqpvalue

```
