---
title: "ACTL90020 Module 8"
output: html_notebook
---

**8.2.1**
```{r}
global = astsa::globtemp

lm.fit = lm(global ~ time(global))
qd.fit = lm(global ~ time(global) + I(time(global)^2))
global.lr = lowess(global)

plot(global,
     main="TS of Global mean land-ocean temperature deviations to 2015",
     sub="Linear Regression fits")
abline(lm.fit, lty = 1, col = "black")
lines(global.lr, lty = 2, col = "blue")
lines(data.frame(x = time(global), y = predict(qd.fit, global)), lty = 3, col="red")
legend("topleft", legend=c("Linear", "Lowess", "Quad"),
       col = c("black", "blue", "red"),
       lty = 1:3)

```
* Linear regression does not fit very well, overally underestimates the 
years before the war and after 1980s. Overestimates years in wars
* Lowess fits better, but still does not reflect the spike in positive
mean land temperature during war
* Quadratic regression is the same as the Lowess


```{r}
years = time(global)
ww1_start = 1914
ww2_end = 1945

war.period = ifelse(years < ww1_start, "Pre War", 
                     ifelse(years>ww2_end, "Post War", "War"))
year.ds = data.frame(year = years, war = war.period)
piecewise.lm = lm(global ~ year*war, data = year.ds)
summary(piecewise.lm)

plot(global,
     main="TS of Global mean land-ocean temperature deviations to 2015",
     sub="Piecewise LR")
# Use fitted()
lines(data.frame(x = years, y = predict(piecewise.lm, year.ds)), 
      lty=2, col="blue")

res = residuals(piecewise.lm)
res.ts = ts(res, start=1880, end=2015)
#par(mfrow=c(2,2))
#plot(piecewise.lm)
plot.ts(res.ts)
par(mar=c(3, 3, 3, 3))
acf(res)

```

**8.2.2**
```{r}
library(astsa)
str(jj)
lm.fit = lm(jj ~ time(jj))
plot(jj)
lines(data.frame(x = time(jj), y = predict(lm.fit, time(jj))), 
      lty=2, col="blue")

res.jj = ts(residuals(lm.fit), start = c(1960, 1), end=c(1981, 4), freq = 4)
plot(res.jj)
acf(res.jj)

```

```{r}

jj.diff = diff(jj)
acf(jj.diff)

```

```{r}

quad.fit = lm(jj ~ time(jj) + I(time(jj)^2))
plot(jj)
lines(data.frame(x = time(jj), y = predict(quad.fit, time(jj))), 
      lty=2, col="blue")

res.jj2 = ts(residuals(quad.fit), start = c(1960, 1), end=c(1981, 4), freq = 4)
plot(res.jj2)
acf(res.jj2)

```


```{r}

jj.log = log(jj)
lmlog.fit = lm(jj.log ~ time(jj))
plot(jj.log)
lines(data.frame(x = time(jj), y = predict(lmlog.fit, time(jj))), 
      lty=2, col="blue")

res.jj3 = ts(residuals(lmlog.fit), start = c(1960, 1), end=c(1981, 4), freq = 4)
plot(res.jj3)
acf(res.jj3)
```

**8.3.2**
```{r}
library(astsa)

cmort.smooth = ksmooth(time(cmort), cmort, bandwidth = 0.5)

plot(cmort)
lines(cmort.smooth, lwd = 2.5, col = "blue")

```

**Using pipelines to try to make cleaner code**
```{r}
library(tidyverse)
library(tsibble)
library(astsa)

global.ts = globtemp %>%
    as_tsibble(.) %>%
    rename(Year = index, Temp = value)

linear.fit = lm(Temp ~ Year, data=global.ts)

global.ts %>%
    ggplot(aes(x = Year,
               y = Temp)) +
        geom_line() + 
        geom_line(aes(x = Year,
                      y = fitted(linear.fit))) +
         scale_x_continuous(name = "Year",
                          breaks = seq(1880, 2020, 20)) + 
        scale_y_continuous(name = "Mean Global Temp")

    

```





